// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApi;

#nullable disable

namespace StoreApi.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20251112223801_invoices")]
    partial class invoices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StoreApi.Models.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Subtotal")
                        .HasColumnType("float");

                    b.Property<double>("Tax")
                        .HasColumnType("float");

                    b.Property<string>("TaxId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingAddress = "Calle Falsa 123, León",
                            BillingEmail = "juan.perez@gmail.com",
                            BillingName = "Juan Pérez",
                            CreatedAt = new DateTime(2025, 11, 2, 16, 37, 59, 618, DateTimeKind.Local).AddTicks(9698),
                            Currency = "MXN",
                            DueDate = new DateTime(2025, 12, 2, 16, 37, 59, 618, DateTimeKind.Local).AddTicks(6507),
                            InvoiceNumber = "INV-1001",
                            IsPaid = false,
                            IssueDate = new DateTime(2025, 11, 2, 16, 37, 59, 616, DateTimeKind.Local).AddTicks(3998),
                            OrderId = 1,
                            Subtotal = 1000.0,
                            Tax = 160.0,
                            TaxId = "XAXX010101000",
                            Total = 1160.0
                        },
                        new
                        {
                            Id = 2,
                            BillingAddress = "Calle Falsa 123, León",
                            BillingEmail = "juan.perez@gmail.com",
                            BillingName = "Juan Pérez",
                            CreatedAt = new DateTime(2025, 11, 7, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(316),
                            Currency = "MXN",
                            DueDate = new DateTime(2025, 12, 7, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(310),
                            InvoiceNumber = "INV-1002",
                            IsPaid = true,
                            IssueDate = new DateTime(2025, 11, 7, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(307),
                            OrderId = 1,
                            PaymentDate = new DateTime(2025, 11, 11, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(314),
                            Subtotal = 500.0,
                            Tax = 80.0,
                            TaxId = "XAXX010101000",
                            Total = 580.0,
                            UpdatedAt = new DateTime(2025, 11, 12, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(317)
                        },
                        new
                        {
                            Id = 3,
                            BillingAddress = "Av. Central 45, León",
                            BillingEmail = "maria.lopez@gmail.com",
                            BillingName = "María López",
                            CreatedAt = new DateTime(2025, 11, 9, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(322),
                            Currency = "MXN",
                            DueDate = new DateTime(2025, 12, 9, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(320),
                            InvoiceNumber = "INV-1003",
                            IsPaid = false,
                            IssueDate = new DateTime(2025, 11, 9, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(319),
                            OrderId = 2,
                            Subtotal = 1200.0,
                            Tax = 192.0,
                            TaxId = "XEXX010101000",
                            Total = 1392.0
                        },
                        new
                        {
                            Id = 4,
                            BillingAddress = "Av. Central 45, León",
                            BillingEmail = "maria.lopez@gmail.com",
                            BillingName = "María López",
                            CreatedAt = new DateTime(2025, 11, 3, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(328),
                            Currency = "MXN",
                            DueDate = new DateTime(2025, 12, 3, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(325),
                            InvoiceNumber = "INV-1004",
                            IsPaid = true,
                            IssueDate = new DateTime(2025, 11, 3, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(324),
                            OrderId = 2,
                            PaymentDate = new DateTime(2025, 11, 5, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(327),
                            Subtotal = 800.0,
                            Tax = 128.0,
                            TaxId = "XEXX010101000",
                            Total = 928.0,
                            UpdatedAt = new DateTime(2025, 11, 5, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(329)
                        },
                        new
                        {
                            Id = 5,
                            BillingAddress = "Av. Central 45, León",
                            BillingEmail = "maria.lopez@gmail.com",
                            BillingName = "María López",
                            CreatedAt = new DateTime(2025, 11, 4, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(333),
                            Currency = "USD",
                            DueDate = new DateTime(2025, 12, 4, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(331),
                            InvoiceNumber = "INV-1005",
                            IsPaid = false,
                            IssueDate = new DateTime(2025, 11, 4, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(330),
                            OrderId = 2,
                            Subtotal = 300.0,
                            Tax = 48.0,
                            TaxId = "XEXX010101000",
                            Total = 348.0
                        },
                        new
                        {
                            Id = 6,
                            BillingAddress = "Blvd. Campestre 500, León",
                            BillingEmail = "carlos.ruiz@gmail.com",
                            BillingName = "Carlos Ruiz",
                            CreatedAt = new DateTime(2025, 11, 5, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(339),
                            Currency = "MXN",
                            DueDate = new DateTime(2025, 12, 5, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(336),
                            InvoiceNumber = "INV-1006",
                            IsPaid = true,
                            IssueDate = new DateTime(2025, 11, 5, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(335),
                            OrderId = 1,
                            PaymentDate = new DateTime(2025, 11, 7, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(338),
                            Subtotal = 1500.0,
                            Tax = 240.0,
                            TaxId = "XAXX010101000",
                            Total = 1740.0,
                            UpdatedAt = new DateTime(2025, 11, 7, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(340)
                        },
                        new
                        {
                            Id = 7,
                            BillingAddress = "Blvd. Campestre 500, León",
                            BillingEmail = "carlos.ruiz@gmail.com",
                            BillingName = "Carlos Ruiz",
                            CreatedAt = new DateTime(2025, 11, 6, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(345),
                            Currency = "MXN",
                            DueDate = new DateTime(2025, 12, 6, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(342),
                            InvoiceNumber = "INV-1007",
                            IsPaid = false,
                            IssueDate = new DateTime(2025, 11, 6, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(341),
                            OrderId = 2,
                            Subtotal = 2200.0,
                            Tax = 352.0,
                            TaxId = "XAXX010101000",
                            Total = 2552.0
                        },
                        new
                        {
                            Id = 8,
                            BillingAddress = "Calle Falsa 123, León",
                            BillingEmail = "juan.perez@gmail.com",
                            BillingName = "Juan Pérez",
                            CreatedAt = new DateTime(2025, 11, 8, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(353),
                            Currency = "USD",
                            DueDate = new DateTime(2025, 12, 8, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(350),
                            InvoiceNumber = "INV-1008",
                            IsPaid = true,
                            IssueDate = new DateTime(2025, 11, 8, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(346),
                            OrderId = 1,
                            PaymentDate = new DateTime(2025, 11, 10, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(352),
                            Subtotal = 900.0,
                            Tax = 144.0,
                            TaxId = "XAXX010101000",
                            Total = 1044.0,
                            UpdatedAt = new DateTime(2025, 11, 10, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(354)
                        },
                        new
                        {
                            Id = 9,
                            BillingAddress = "Calle Falsa 123, León",
                            BillingEmail = "juan.perez@gmail.com",
                            BillingName = "Juan Pérez",
                            CreatedAt = new DateTime(2025, 11, 10, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(359),
                            Currency = "MXN",
                            DueDate = new DateTime(2025, 12, 10, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(356),
                            InvoiceNumber = "INV-1009",
                            IsPaid = false,
                            IssueDate = new DateTime(2025, 11, 10, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(355),
                            OrderId = 1,
                            Subtotal = 400.0,
                            Tax = 64.0,
                            TaxId = "XAXX010101000",
                            Total = 464.0
                        },
                        new
                        {
                            Id = 10,
                            BillingAddress = "Av. Central 45, León",
                            BillingEmail = "maria.lopez@gmail.com",
                            BillingName = "María López",
                            CreatedAt = new DateTime(2025, 11, 11, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(364),
                            Currency = "MXN",
                            DueDate = new DateTime(2025, 12, 11, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(361),
                            InvoiceNumber = "INV-1010",
                            IsPaid = true,
                            IssueDate = new DateTime(2025, 11, 11, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(361),
                            OrderId = 2,
                            PaymentDate = new DateTime(2025, 11, 12, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(363),
                            Subtotal = 1100.0,
                            Tax = 176.0,
                            TaxId = "XEXX010101000",
                            Total = 1276.0,
                            UpdatedAt = new DateTime(2025, 11, 12, 16, 37, 59, 619, DateTimeKind.Local).AddTicks(365)
                        });
                });

            modelBuilder.Entity("StoreApi.Models.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SystemUserId")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("StoreApi.Models.Entities.OrderProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.HasKey("ProductId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("StoreApi.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Calzado típico de León",
                            Name = "Zapatos de piel",
                            Price = 1200.0,
                            StoreId = 4
                        },
                        new
                        {
                            Id = 2,
                            Description = "Artesanía local",
                            Name = "Bolsa de cuero",
                            Price = 950.0,
                            StoreId = 4
                        },
                        new
                        {
                            Id = 3,
                            Description = "Comida rápida",
                            Name = "Hamburguesa doble",
                            Price = 120.0,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Especialidad italiana",
                            Name = "Pizza familiar",
                            Price = 220.0,
                            StoreId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Taza grande",
                            Name = "Café americano",
                            Price = 45.0,
                            StoreId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "Bebida refrescante",
                            Name = "Refresco 600ml",
                            Price = 20.0,
                            StoreId = 5
                        });
                });

            modelBuilder.Entity("StoreApi.Models.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Plaza Mayor León",
                            Latitude = 21.154,
                            Longitude = -101.69459999999999
                        },
                        new
                        {
                            Id = 2,
                            Description = "Centro Max",
                            Latitude = 21.094799999999999,
                            Longitude = -101.6417
                        },
                        new
                        {
                            Id = 3,
                            Description = "Plaza Galerías Las Torres",
                            Latitude = 21.121099999999998,
                            Longitude = -101.6613
                        },
                        new
                        {
                            Id = 4,
                            Description = "Outlet Mulza",
                            Latitude = 21.0459,
                            Longitude = -101.58620000000001
                        },
                        new
                        {
                            Id = 5,
                            Description = "La Gran Plaza León",
                            Latitude = 21.128,
                            Longitude = -101.6827
                        },
                        new
                        {
                            Id = 6,
                            Description = "Altacia :)",
                            Latitude = 21.128,
                            Longitude = -102.0
                        });
                });

            modelBuilder.Entity("StoreApi.Models.Entities.SystemUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "juan@gmail.com",
                            FirstName = "Juan",
                            LastName = "Juan",
                            Password = "123456"
                        });
                });

            modelBuilder.Entity("StoreApi.Models.Entities.Invoice", b =>
                {
                    b.HasOne("StoreApi.Models.Entities.Order", "Order")
                        .WithMany("Invoices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("StoreApi.Models.Entities.Order", b =>
                {
                    b.HasOne("StoreApi.Models.Entities.SystemUser", "SystemUser")
                        .WithMany("Orders")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("StoreApi.Models.Entities.OrderProduct", b =>
                {
                    b.HasOne("StoreApi.Models.Entities.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreApi.Models.Entities.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreApi.Models.Entities.Product", b =>
                {
                    b.HasOne("StoreApi.Models.Entities.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("StoreApi.Models.Entities.Order", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("StoreApi.Models.Entities.Product", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("StoreApi.Models.Entities.Store", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("StoreApi.Models.Entities.SystemUser", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
